'use client'

import Link from 'next/link'
import { TriangleAlert as AlertTriangle, ArrowLeft, ArrowRight, Award, Bookmark, Check, ChevronDown, Clock3, Copy, Download, Dumbbell, Leaf, Share2, ShieldCheck, Sparkles, Timer, Trophy, X, Zap } from 'lucide-react'
import { useState } from 'react'
import type { Recipe } from '@/lib/types'

export const dietStyles = ['ไม่กำหนด (กินทั่วไป)', 'IF (Intermittent Fasting)', 'High Protein (เน้นโปรตีนสูง)', 'Low Carb (ลดแป้ง/น้ำตาล)', 'Keto (คีโตเจนิค - คาร์บต่ำมาก)', 'Mediterranean (เน้นไขมันดี/ปลา/ผัก)', 'DASH Diet (เน้นลดความดัน/ลดโซเดียม)', 'Clean Eating (อาหารธรรมชาติแปรรูปน้อย)', 'Vegan / Vegetarian (มังสวิรัติ)', 'Pescatarian (มังสวิรัติทานปลา)']
export const activities = ['ขยับตัวน้อยมาก', 'เคลื่อนไหวเบาๆ', 'ออกกำลังกายปานกลาง', 'ออกกำลังกายหนัก', 'นักกีฬา / งานใช้แรงงานหนัก']
export const activityDescriptions = ['นั่งทำงานอยู่กับโต๊ะเป็นหลัก แทบไม่ได้ออกกำลังกายเลย', 'เดินบ้าง ทำงานบ้าน หรือออกกำลังกายเบาๆ 1-2 วัน/สัปดาห์', 'ขยับร่างกายบ่อย หรือออกกำลังกาย 3-5 วัน/สัปดาห์', 'เล่นกีฬาเป็นประจำ หรือออกกำลังกายหนัก 6-7 วัน/สัปดาห์', 'ซ้อมหนักวันละหลายครั้ง หรือใช้แรงงานตลอดวัน']
export const ingredientGroups = [{ title: 'ของสด', items: ['อกไก่', 'ไข่ไก่', 'เต้าหู้', 'ปลาแซลมอน'] }, { title: 'ผักและธัญพืช', items: ['บรอกโคลี', 'ผักโขม', 'อะโวคาโด', 'ข้าวกล้อง'] }]
export const recipes = [{ rank: 'อันดับ 1', label: 'แนะนำมากที่สุดสำหรับคุณ', icon: Trophy, tone: 'gold', title: 'ข้าวกล้องหน้าไก่ย่างผักรวม', time: '20 นาที', kcal: 480, macros: ['38g', '48g', '12g'], ingredients: ['อกไก่ 150 กรัม', 'ข้าวกล้อง 100 กรัม', 'บรอกโคลี 80 กรัม', 'น้ำมันมะกอก 1 ช้อนชา'], allergens: [], steps: ['หมักอกไก่ด้วยพริกไทยและซีอิ๊วโซเดียมต่ำ 5 นาที', 'ย่างไก่ด้วยไฟกลางจนสุกทั่วถึง แล้วหั่นเป็นชิ้นพอดีคำ', 'ลวกบรอกโคลีและจัดเสิร์ฟคู่ข้าวกล้อง'] }, { rank: 'อันดับ 2', label: 'ทางเลือกสุขภาพดี', icon: Dumbbell, tone: 'green', title: 'แซลมอนอะโวคาโดโบวล์', time: '15 นาที', kcal: 520, macros: ['34g', '42g', '18g'], ingredients: ['ปลาแซลมอน 120 กรัม', 'อะโวคาโดครึ่งผล', 'ควินัว 80 กรัม', 'มะนาว 1 ซีก'], allergens: ['ปลา'], steps: ['อบแซลมอนที่ 180°C ประมาณ 12 นาที', 'ต้มควินัวและพักให้สะเด็ดน้ำ', 'จัดทุกอย่างลงชาม เติมมะนาวเล็กน้อย'] }, { rank: 'อันดับ 3', label: 'ทำง่ายรวดเร็ว', icon: Timer, tone: 'blue', title: 'เต้าหู้ผัดผักไขมันต่ำ', time: '10 นาที', kcal: 310, macros: ['22g', '28g', '11g'], ingredients: ['เต้าหู้แข็ง 150 กรัม', 'ไข่ไก่ 1 ฟอง', 'ผักโขม 80 กรัม', 'น้ำมันมะกอกครึ่งช้อนชา'], allergens: ['ถั่วเหลือง', 'ไข่'], steps: ['หั่นเต้าหู้เป็นชิ้นและซับน้ำออก', 'ผัดผักโขมด้วยน้ำมันมะกอกเล็กน้อย', 'ใส่เต้าหู้และไข่ ปรุงรสโซเดียมต่ำ'] }]

export function Logo() { return <Link href="/" className="logo" aria-label="AI Nutrition หน้าแรก"><span className="logo-mark"><Leaf /></span><span>AI <span>Nutrition</span></span></Link> }
export function BackLink({ href, children = 'ย้อนกลับ' }: { href: string; children?: React.ReactNode }) { return <Link href={href} className="back-link"><ArrowLeft />{children}</Link> }
export function FlowHeader({ step }: { step: number }) { return <header className="flow-header shell"><Logo /><nav className="flow-steps" aria-label="ขั้นตอนการตั้งค่า">{['โปรไฟล์สุขภาพ', 'เลือกวัตถุดิบ', 'AI ประมวลผล'].map((label, i) => <div key={label} className={`flow-step ${i + 1 <= step ? 'active' : ''}`}><span>{i + 1 <= step ? <Check /> : i + 1}</span>{label}</div>)}</nav></header> }
export function PrimaryButton({ children, href, onClick, type = 'button', disabled = false }: { children: React.ReactNode; href?: string; onClick?: () => void; type?: 'button' | 'submit'; disabled?: boolean }) { return href ? <Link href={href} className="primary-button">{children}</Link> : <button type={type} onClick={onClick} className="primary-button" disabled={disabled}>{children}</button> }
export function TagInput({ label, tags, onChange, placeholder }: { label: string; tags: string[]; onChange: (tags: string[]) => void; placeholder: string }) { const [value, setValue] = useState(''); const add = () => { const item = value.trim(); if (item && !tags.includes(item)) onChange([...tags, item]); setValue('') }; return <div className="tag-field"><label>{label}</label><div className="tag-input"><div className="chip-row">{tags.map(tag => <button type="button" className="chip selected" key={tag} onClick={() => onChange(tags.filter(item => item !== tag))}>{tag}<X /></button>)}</div><div className="tag-entry"><input value={value} placeholder={placeholder} onChange={e => setValue(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); add() } }} /><button type="button" onClick={add} aria-label={`เพิ่ม${label}`}>+</button></div></div></div> }
export function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="page-intro"><div className="kicker"><Sparkles />{eyebrow}</div><h1>{title}</h1><p>{description}</p></div> }

function ShareModal({ recipe, onClose }: { recipe: Recipe; onClose: () => void }) { const [copied, setCopied] = useState(false); const share = async () => { if (navigator.share) await navigator.share({ title: recipe.title, text: `${recipe.title} · ${recipe.kcal} kcal` }); else { await navigator.clipboard.writeText(`${recipe.title} · ${recipe.kcal} kcal`); setCopied(true) } }; const download = () => { const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="900"><rect width="100%" height="100%" fill="#f1f3e0"/><text x="60" y="100" font-family="sans-serif" font-size="25" fill="#496653">AI Nutrition</text><text x="60" y="220" font-family="sans-serif" font-size="44" font-weight="bold" fill="#203129">${recipe.title}</text><text x="60" y="290" font-family="sans-serif" font-size="28" fill="#496653">${recipe.kcal} kcal · ${recipe.time}</text><text x="60" y="370" font-family="sans-serif" font-size="22" fill="#203129">โปรตีน ${recipe.macros[0]}  คาร์บ ${recipe.macros[1]}  ไขมัน ${recipe.macros[2]}</text><text x="60" y="470" font-family="sans-serif" font-size="22" fill="#496653">วัตถุดิบ</text>${recipe.ingredients.map((item, i) => `<text x="60" y="${510 + i * 34}" font-family="sans-serif" font-size="18" fill="#203129">• ${item}</text>`).join('')}<text x="60" y="700" font-family="sans-serif" font-size="20" fill="#496653">ปลอดภัยสำหรับเป้าหมายสุขภาพของคุณ</text></svg>`; const url = URL.createObjectURL(new Blob([svg], { type: 'image/svg+xml' })); const link = document.createElement('a'); link.href = url; link.download = 'ai-nutrition-meal.svg'; link.click(); URL.revokeObjectURL(url) }; return <div className="share-overlay" role="dialog" aria-modal="true" aria-label="แชร์เมนูอาหาร"><div className="share-modal"><button className="modal-close" onClick={onClose} aria-label="ปิด"><X /></button><div className="story-card"><Logo /><span className="story-kicker">Healthy Meal Recipe</span><h2>{recipe.title}</h2><strong>{recipe.kcal} kcal</strong><div className="story-macros"><span>โปรตีน <b>{recipe.macros[0]}</b></span><span>คาร์บ <b>{recipe.macros[1]}</b></span><span>ไขมัน <b>{recipe.macros[2]}</b></span></div><div className="story-section"><b>วัตถุดิบ</b>{recipe.ingredients.slice(0, 3).map(item => <small key={item}>{item}</small>)}</div>{recipe.allergens.length > 0 && <div className="story-warning"><AlertTriangle />มีส่วนผสมของ {recipe.allergens.join(' / ')}</div>}<div className="story-safe"><ShieldCheck />ปลอดภัยสำหรับเป้าหมายสุขภาพของคุณ</div></div><div className="modal-actions"><button className="primary-button" onClick={download}><Download />ดาวน์โหลดรูปภาพ</button><button className="secondary-button" onClick={share}><Share2 />{copied ? 'คัดลอกลิงก์แล้ว' : 'แชร์ไปยัง Social Media'}{copied && <Copy />}</button></div></div></div> }

export function RecipeCard({ recipe }: { recipe: Recipe }) { const [open, setOpen] = useState(false); const [saved, setSaved] = useState(false); const [sharing, setSharing] = useState(false); const Icon = recipe.icon; return <article className="result-card"><div className={`rank-line ${recipe.tone}`}><span className="rank-badge"><Icon />{recipe.rank}</span><span className="rank-label">{recipe.label}</span></div><div className="result-card-head"><div><span className="pill"><Clock3 />{recipe.time} · {recipe.kcal} kcal</span><h3>{recipe.title}</h3></div><div className="recipe-badge"><Leaf /></div></div><div className="macro-row result-macros">{['โปรตีน', 'คาร์บ', 'ไขมัน'].map((label, i) => <span key={label}><b>{label}</b>{recipe.macros[i]}</span>)}</div><section className="detail-block"><h4>วัตถุดิบปริมาณที่แนะนำ</h4><ul>{recipe.ingredients.map(item => <li key={item}>{item}</li>)}</ul>{recipe.allergens.length > 0 && <div className="allergen-note"><AlertTriangle />มีส่วนผสมของ {recipe.allergens.join(' / ')}</div>}</section><button className="accordion-trigger" onClick={() => setOpen(!open)} aria-expanded={open}>วิธีทำทีละขั้นตอน <ChevronDown className={open ? 'rotate' : ''} /></button>{open && <ol className="recipe-steps">{recipe.steps.map((step, i) => <li key={step}><span>{i + 1}</span>{step}</li>)}</ol>}<div className="safety-note"><ShieldCheck /><div><strong>ปลอดภัยสำหรับเป้าหมายของคุณ</strong><p>{recipe.safetyNote}</p></div></div><div className="recipe-actions"><button type="button" className="save-button" onClick={() => setSaved(!saved)}><Bookmark />{saved ? 'บันทึกแล้ว' : 'บันทึกมื้ออาหารนี้'}</button><button type="button" className="share-button" onClick={() => setSharing(true)}><Share2 />แชร์เมนูนี้</button></div>{sharing && <ShareModal recipe={recipe} onClose={() => setSharing(false)} />}</article> }
export const ArrowIcon = ArrowRight
export const AwardIcon = Award
export const ZapIcon = Zap
